In [1]:
##build a clinical prediction model using logistic regression


import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score


In [5]:
from sklearn.datasets import load_diabetes

data = load_diabetes()
X = data.data
y = (data.target > 140).astype(int)  # Binary classification (diabetes or not)


In [6]:
import pandas as pd
from sklearn.datasets import load_diabetes

data = load_diabetes()
diabetes_df = pd.DataFrame(data.data, columns=data.feature_names)

# Access the first 5 rows
first_5_entries = diabetes_df.head(5)
print(first_5_entries)


        age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  
0 -0.002592  0.019907 -0.017646  
1 -0.039493 -0.068332 -0.092204  
2 -0.002592  0.002861 -0.025930  
3  0.034309  0.022688 -0.009362  
4 -0.002592 -0.031988 -0.046641  


In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [9]:
X_test[1]

array([ 1.96942617, -0.94217861,  0.74501508,  0.42754112, -0.51143404,
       -0.33328244,  0.03763145, -0.83545839, -0.4969087 , -0.49013439])

In [10]:
model = LogisticRegression()
model.fit(X_train, y_train)


LogisticRegression()

In [14]:
y_pred = model.predict(X_test)
y_pred 

array([0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1])

In [15]:
accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_rep)


Accuracy: 0.7303370786516854

Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.73      0.75        49
           1       0.69      0.72      0.71        40

    accuracy                           0.73        89
   macro avg       0.73      0.73      0.73        89
weighted avg       0.73      0.73      0.73        89



In [16]:
#build a clinical prediction model using random forest
from sklearn.ensemble import RandomForestClassifier
# Create and train a Random Forest classifier
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("\nClassification Report:\n", classification_rep)


Accuracy: 0.7191011235955056

Classification Report:
               precision    recall  f1-score   support

           0       0.74      0.76      0.75        49
           1       0.69      0.68      0.68        40

    accuracy                           0.72        89
   macro avg       0.72      0.72      0.72        89
weighted avg       0.72      0.72      0.72        89



In [17]:
y_pred

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1])

In [22]:
pip install tensorflow


     -------------------------------------- 284.1/284.1 MB 3.7 MB/s eta 0:00:00
     -------------------------------------- 430.5/430.5 kB 5.4 MB/s eta 0:00:00
     ---------------------------------------- 65.5/65.5 kB 3.7 MB/s eta 0:00:00
     ---------------------------------------- 57.5/57.5 kB 3.0 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 5.4 MB/s eta 0:00:00
     ---------------------------------------- 5.5/5.5 MB 5.9 MB/s eta 0:00:00
     -------------------------------------- 938.6/938.6 kB 6.6 MB/s eta 0:00:00
     ---------------------------------------- 3.7/3.7 MB 5.0 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 4.5 MB/s eta 0:00:00
     -------------------------------------- 440.7/440.7 kB 4.6 MB/s eta 0:00:00
     ---------------------------------------- 130.2/130.2 kB ? eta 0:00:00
     -------------------------------------- 182.3/182.3 kB 5.6 MB/s eta 0:00:00
     -------------------------------------- 151.7/

In [20]:
pip install keras


     ---------------------------------------- 1.7/1.7 MB 3.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [23]:
#build a clinical prediction model using neural network

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from keras.layers import Dense


In [24]:
from sklearn.datasets import load_diabetes

data = load_diabetes()
X = data.data
y = (data.target > 140).astype(int)  # Binary classification (diabetes or not)


In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [26]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [27]:
model = Sequential()
model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_train, y_train, epochs=20, batch_size=32)


Epoch 1/20
12/12 [==============================] - 1s 4ms/step - loss: 0.6954 - accuracy: 0.5496
Epoch 2/20
12/12 [==============================] - 0s 5ms/step - loss: 0.6176 - accuracy: 0.6884
Epoch 3/20
12/12 [==============================] - 0s 5ms/step - loss: 0.5742 - accuracy: 0.7365
Epoch 4/20
12/12 [==============================] - 0s 5ms/step - loss: 0.5432 - accuracy: 0.7479
Epoch 5/20
12/12 [==============================] - 0s 5ms/step - loss: 0.5237 - accuracy: 0.7507
Epoch 6/20
12/12 [==============================] - 0s 5ms/step - loss: 0.5072 - accuracy: 0.7450
Epoch 7/20
12/12 [==============================] - 0s 4ms/step - loss: 0.4978 - accuracy: 0.7479
Epoch 8/20
12/12 [==============================] - 0s 4ms/step - loss: 0.4883 - accuracy: 0.7564
Epoch 9/20
12/12 [==============================] - 0s 4ms/step - loss: 0.4802 - accuracy: 0.7592
Epoch 10/20
12/12 [==============================] - 0s 3ms/step - loss: 0.4734 - accuracy: 0.7592
Epoch 11/20
12/12 [

In [28]:
accuracy = model.evaluate(X_test, y_test)[1]
print("Accuracy:", accuracy)


3/3 [==============================] - 0s 6ms/step - loss: 0.5042 - accuracy: 0.7079
Accuracy: 0.7078651785850525


In [30]:
import pandas as pd
from sklearn.datasets import load_diabetes

# Load the Diabetes dataset
data = load_diabetes()
X = data.data
y = (data.target > 140).astype(int)  # Binary classification (diabetes or not)

# Convert to a Pandas DataFrame
diabetes_df = pd.DataFrame(data.data, columns=data.feature_names)
diabetes_df['target'] = y  # Add the target column

# Specify the full path to save the CSV file on your PC
file_path = 'C:/Users/Karthik/Desktop/not/medical_notes_generator-master/medical_notes_generator-master/diabetes_dataset.csv'  # Replace with your desired directory and file name

# Save the dataset as a CSV file
diabetes_df.to_csv(file_path, index=False)
